version: '3.8'

services:
  bot:
    image: abdulaziz/coffeebot:latest  # غيّر حسب repo اسمك
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      # اقرأ من mounted secrets أو env variables على Portainer
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - ADMIN_IDS=${ADMIN_IDS}
      - ADMIN_GROUP_ID=${ADMIN_GROUP_ID}
      - LOG_LEVEL=${LOG_LEVEL}
      - TZ=Asia/Riyadh
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
